 const errorNames = {
	VALIDATION_ERROR: "VALIDATION_ERROR:",
	VALIDATION_CUSTOM: "VALIDATION_CUSTOM:",
	SILENT: "SILENT:",
	REDIRECT: "REDIRECT:",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR:",
	NOT_ALLOWED: "NOT_ALLOWED:",
	NOT_FOUND: "NOT_FOUND:",
	INCORRECT_VALUES: "INCORRECT_VALUES:",
};
module.exports = errorNames;